---
# tasks file for ansible-role-dell

 - name: add Dell DSU repo
   template: src=dell-system-update-repository.repo.j2 dest=/etc/yum.repos.d/dell-system-update-repository.repo mode=0644 owner=root backup=yes

 - name: install Dell DSU Key
   rpm_key: key=http://linux.dell.com/repo/hardware/dsu/public.key state=present

 - name: install packages
   yum: pkg={{ item }}
   with_items: dell_packages
   when: dell_packages.0 != ""

 - name: copy in idrac csc helper scripts
   copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755 owner=root group=root backup=no
   with_items: dell_helper_scripts
   when: dell_helper_scripts.0 != "" and dell_install_helper_scripts

 - name: copy remote console app binary
   copy: src=file/remoteConsoleLoader dest=/root/remoteConsoleLoader mode=0755 owner=root group=root backup=no
